spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/est_oauth_exp_1
    username: happy
    password: day

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show_sql: true
      format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile




